version: '3.8'
services:
  postgres_test:
    image: postgres:13
    ports:
      - "5433:5433"  # Different port for test database
    environment:
      POSTGRES_DB: loan_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data: 